const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,f);
require.extensions['.css']=()=>{};
const {renderToStaticMarkup}=require('react-dom/server'),home=require('../app/page.tsx');
const html=renderToStaticMarkup(home.default());
assert(html.includes('Kartu Google Review.'));
assert(html.includes('kartu QR &amp; NFC'));
assert(html.includes('href="/dashboard"'),'Customers can still reach the dashboard');
assert(!html.includes('http-equiv="refresh"'),'Search crawlers must receive real product content, not a login redirect');
assert.equal((html.match(/<h1\b/g)||[]).length,1);
assert.equal(home.metadata.robots.index,true);
assert.equal(home.metadata.alternates.canonical,'https://yukreview.id');
assert(home.metadata.title.includes('Kartu Google Review'));
assert(home.metadata.description.includes('Google Review QR & NFC'));
const schema=JSON.parse(html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)[1]);
assert.equal(schema['@graph'][0].url,'https://yukreview.id');
assert.equal(schema['@graph'][0].name,'YukReview');
assert(!schema['@graph'].some(x=>x.aggregateRating),'No fabricated ratings or reviews');
const sitemap=require('../app/sitemap.ts').default();
assert.deepEqual(sitemap.map(x=>x.url),['https://yukreview.id'],'Customer and provider records must never enter the marketing sitemap');
assert.equal(require('../app/robots.ts').default().sitemap,'https://yukreview.id/sitemap.xml');
for(const file of ['app/dashboard/layout.tsx','app/activate/layout.tsx','app/provider/layout.tsx','app/access/layout.tsx'])assert(fs.readFileSync(file,'utf8').match(/index:\s*false/),'Private app surfaces retain noindex: '+file);
console.log('PASS public homepage SEO: real product content, dashboard access, canonical/title/description, structured brand data, public-only sitemap and private noindex');
