const fs=require('node:fs'),ts=require('typescript'),Module=require('node:module'),assert=require('node:assert/strict');
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,f);
require.extensions['.css']=()=>{};
const React=require('react'),{act,create}=require('react-test-renderer');global.IS_REACT_ACT_ENVIRONMENT=true;
let account='owner@example.com',business='business-a',switchBusiness,saveFails=false,googleCalls=0,calls=[],lateResolve,authCallback,lateSaveResolve,delaySave=false,throwSave=false;
const storage=new Map();global.window={sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}};
global.fetch=async()=>{googleCalls++;return {ok:true,json:async()=>({success:true,maps_url:'https://maps.app.goo.gl/draft'})};};
const supabase={auth:{getSession:async()=>({data:{session:{user:{email:account},access_token:'token'}}}),onAuthStateChange:callback=>{authCallback=callback;return ({data:{subscription:{unsubscribe(){}}}});}},rpc:async(name,args)=>{
 calls.push({name,args});
 if(name==='v3_update_business_display_name'&&throwSave)throw Error('offline');
 if(name==='v3_update_business_display_name'&&delaySave)return new Promise(resolve=>{lateSaveResolve=resolve;});
 if(name==='v3_get_landing_page_settings'&&args.p_business_id==='business-late')return new Promise(resolve=>{lateResolve=resolve;});
 if(name==='v3_get_business_profile')return {data:{success:true,display_name:'Server name'},error:null};
 if(name==='v3_get_business_contact_settings')return {data:{whatsapp_number:'628111'},error:null};
 if(name==='v3_get_landing_page_settings')return {data:{hero_title:'Server title'},error:null};
 if(name==='v3_update_business_display_name'&&saveFails)return {data:null,error:{message:'offline'}};
 return {data:{success:true},error:null};
}};
const original=Module._load;
Module._load=function(id,parent,main){
 if(id.endsWith('/lib/supabase'))return {supabase};
 if(id.endsWith('/lib/i18n'))return {useLanguage:()=>({tr:id=>id})};
 if(id.endsWith('/lib/useBusinessContext'))return {useBusinessContext:()=>{
   const [id,setId]=React.useState(business);switchBusiness=setId;
   return {businessId:id,setBusinessId:setId,businesses:[{business_id:id,business_name:'Business'}],businessLoading:false,businessError:''};
 }};
 return original.call(this,id,parent,main);
};
const Page=require('../app/dashboard/landing-page/page.tsx').default;
const {landingDraftKey,writeLandingDraft}=require('../lib/landingDraft.ts');
const text=node=>!node?'':typeof node==='string'?node:Array.isArray(node)?node.map(text).join(' '):text(node.children);
(async()=>{
 let tree;
 const mount=async()=>{await act(async()=>{tree=create(React.createElement(Page));});};
 const input=placeholder=>tree.root.findAll(n=>n.props.placeholder===placeholder)[0];
 await mount();
 assert.equal(storage.size,0,'Initial server load must not create a stale draft');
 assert.equal(writeLandingDraft('oversized',{value:'x'.repeat(65536)}),false);
 assert(!storage.has('oversized'),'Cannot report a draft saved if the reader cannot restore it');
 const fields=['Judul utama','Tentang bisnis'];
 await act(async()=>{
   input(fields[0]).props.onChange({target:{value:'Unsaved title'}});
   input(fields[1]).props.onChange({target:{value:'Unsaved about'}});
   tree.root.findAllByType('input').find(n=>n.props.value==='Server name').props.onChange({target:{value:'Unsaved business'}});
   tree.root.findAllByType('input').find(n=>n.props.value==='628111').props.onChange({target:{value:'628999'}});
   tree.root.findAllByType('input').find(n=>n.props.placeholder==='https://maps.app.goo.gl/...').props.onChange({target:{value:'https://maps.app.goo.gl/draft'}});
   tree.root.findAllByType('input').find(n=>n.props.type==='checkbox').props.onChange({target:{checked:false}});
 });
 const keyA=landingDraftKey(account,business);
 assert(storage.has(keyA));assert.equal(googleCalls,0,'Typing and draft saving must not consume Google quota');
 await act(async()=>tree.unmount());await mount();
 assert.equal(input(fields[0]).props.value,'Unsaved title');assert.equal(input(fields[1]).props.value,'Unsaved about');
 assert(tree.root.findAllByType('input').some(n=>n.props.value==='Unsaved business'));
 assert(tree.root.findAllByType('input').some(n=>n.props.value==='628999'));
 assert(tree.root.findAllByType('input').some(n=>n.props.value==='https://maps.app.goo.gl/draft'));
 assert.equal(tree.root.findAllByType('input').find(n=>n.props.type==='checkbox').props.checked,false);
 assert.equal(googleCalls,0,'Restoration must not call Google');
 await act(async()=>switchBusiness('business-b'));
 assert.equal(input(fields[0]).props.value,'Server title');
 await act(async()=>input(fields[0]).props.onChange({target:{value:'Business B draft'}}));
 await act(async()=>switchBusiness('business-a'));
 assert.equal(input(fields[0]).props.value,'Unsaved title');
 await act(async()=>switchBusiness('business-late'));
 assert.equal(tree.root.findAllByType('input').length,0,'Previous business fields must be hidden while new business loads');
 await act(async()=>switchBusiness('business-a'));
 await act(async()=>lateResolve({data:{hero_title:'Late response'},error:null}));
 assert.equal(input(fields[0]).props.value,'Unsaved title','Late business response must not overwrite the current draft');
 saveFails=true;
 await act(async()=>tree.root.findByType('form').props.onSubmit({preventDefault(){}}));
 assert(storage.has(keyA),'Failed save must retain draft');
 saveFails=false;
 await act(async()=>tree.root.findByType('form').props.onSubmit({preventDefault(){}}));
 assert(!storage.has(keyA),'Successful full save clears that draft');
 assert(storage.has(landingDraftKey(account,'business-b')),'Other business draft remains');
 assert.equal(googleCalls,1);
 throwSave=true;
 await act(async()=>input(fields[0]).props.onChange({target:{value:'Keep on thrown network failure'}}));
 await act(async()=>tree.root.findByType('form').props.onSubmit({preventDefault(){}}));
 assert(storage.has(keyA));assert(JSON.stringify(tree.toJSON()).includes('Periksa koneksi'));
 assert.equal(tree.root.findByType('fieldset').props.disabled,false,'Thrown save must release busy state');
 throwSave=false;delaySave=true;
 let savePromise;
 await act(async()=>{savePromise=tree.root.findByType('form').props.onSubmit({preventDefault(){}});});
 const writesBefore=calls.filter(c=>c.name==='v3_update_business_contact_settings').length;
 account='switched@example.com';
 await act(async()=>authCallback('SIGNED_IN',{user:{email:account}}));
 await act(async()=>{lateSaveResolve({data:{success:true,display_name:'OLD account response'},error:null});await savePromise;});
 assert.equal(calls.filter(c=>c.name==='v3_update_business_contact_settings').length,writesBefore,'Account switch must stop remaining old save steps');
 assert(!JSON.stringify(tree.toJSON()).includes('OLD account response'));
 assert.equal(input(fields[0]).props.value,'Server title');
 delaySave=false;account='owner@example.com';
 await act(async()=>authCallback('SIGNED_IN',{user:{email:account}}));
 await act(async()=>input(fields[0]).props.onChange({target:{value:'Owner A private draft'}}));
 await act(async()=>tree.unmount());account='other@example.com';await mount();
 assert.equal(input(fields[0]).props.value,'Server title','Different account cannot restore previous account draft');
 await act(async()=>tree.unmount());account='owner@example.com';
 storage.set(keyA,'{bad json');await mount();assert.equal(input(fields[0]).props.value,'Server title');
 window.sessionStorage.setItem=()=>{throw Error('blocked');};
 await act(async()=>input(fields[0]).props.onChange({target:{value:'Still editable'}}));
 assert(text(tree.toJSON()).includes('Browser tidak dapat menyimpan draft'));
 assert.equal(input(fields[0]).props.value,'Still editable');
 await act(async()=>tree.unmount());
 console.log('PASS editor drafts: refresh restoration of text/contact/Maps/toggles, business/account isolation, failed/successful save, no automatic Google calls, malformed/blocked storage');
})().catch(error=>{console.error(error);process.exitCode=1;});
